# Generated by Django 2.0.1 on 2018-01-12 21:47

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('diaryid', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('hours', models.FloatField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('completed', models.DateField(blank=True, null=True)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='low', max_length=4)),
                ('point', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('comment', models.TextField(blank=True, null=True)),
                ('staff', models.ManyToManyField(blank=True, to='caretaking.Staff')),
            ],
            options={
                'get_latest_by': 'completed',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('typeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='tasktype',
            field=models.ManyToManyField(blank=True, to='caretaking.TaskType'),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='caretaking.Staff'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='caretaking.Staff'),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, to='caretaking.Task'),
        ),
        migrations.AddField(
            model_name='diary',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='caretaking.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='diary',
            unique_together={('day', 'staff')},
        ),
    ]
