# Generated by Django 2.0.1 on 2018-01-25 07:28

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('diaryid', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.DateField(help_text='The date of this diary entry')),
                ('hours', models.FloatField(help_text='The hours worked this day')),
                ('comment', models.TextField(blank=True, help_text='A summary comment about this day', null=True)),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('locationid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Useful name for this location - by convention uses CamelCase', max_length=50)),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(help_text='Polygon or Multipolygon', srid=4326)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('projectid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A short descriptive name', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Long description', null=True)),
                ('comment', models.TextField(blank=True, help_text='Any additional comments', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='The job title of this staff member', max_length=50)),
                ('comment', models.TextField(blank=True, help_text='Relevant useful information about this staff member', null=True)),
                ('user', models.OneToOneField(help_text='The authentication backend user of the application', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('taskid', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='A descriptive summary of the task')),
                ('completed', models.DateField(blank=True, help_text='The date completed', null=True)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('med', 'Medium'), ('high', 'High')], default='low', help_text='The urgency of the task', max_length=4)),
                ('point', django.contrib.gis.db.models.fields.GeometryField(blank=True, help_text='Point or Multipoint for the task', null=True, srid=4326)),
                ('staff', models.ForeignKey(blank=True, help_text='Staff member performing the work', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='caretaking.Staff')),
            ],
            options={
                'get_latest_by': 'completed',
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('typeid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='A short descriptive name', max_length=50)),
                ('comment', models.TextField(blank=True, help_text='Additional descriptive comment', null=True)),
            ],
            options={
                'verbose_name': 'Task Type',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='tasktype',
            field=models.ManyToManyField(help_text='One or more types', to='caretaking.TaskType'),
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The staff member to whom the project is assigned', null=True, on_delete=django.db.models.deletion.CASCADE, to='caretaking.Staff'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(help_text='The staff member who creates the project', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='caretaking.Staff'),
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(help_text='The individual tasks that make up the project', to='caretaking.Task'),
        ),
        migrations.AddField(
            model_name='diary',
            name='staff',
            field=models.ForeignKey(help_text='The staff member of this diary entry', on_delete=django.db.models.deletion.DO_NOTHING, to='caretaking.Staff'),
        ),
        migrations.AlterUniqueTogether(
            name='diary',
            unique_together={('day', 'staff')},
        ),
    ]
